### PR TITLE
Small change to text within source/global/index.rst 

### PR DESCRIPTION
**Pull request by roberts-luke**
Hi Bjoern, 

These changes are very minor, but are just for testing my git working practices. 

I made a few changes to text in the global tutorial, then ran:
git add
git commit
git push

Now I am launching a pull request for you to review to merge to main.

### CODE REVIEW

**Comment by BHFock** [comment]
Please change the commit message to make it about describing the change and not the purpose of the change, e.g. write about British English and about clarification of the words model and workflow.

**Comment by BHFock** [comment]
Also adjust the title of the pull request to make it more descriptive.

**Comment by roberts-luke** [comment]
@BHFock title and description updated

**Comment by BHFock** [comment]
Thanks @roberts-luke. I will pull the requested changes now.

**Pull request merged**
